### ISSUE TITLE
OffsetDateTime and ZonedDateTime support

### ISSUE THREAD

**Issue by gontard** [arangodb/java-velocypack-module-jdk8#2]
Hello,

thanks for this module.
Have you considered to add the support of others date types ?
- `java.time.ZonedDateTime`
- `java.time.OffsetDateTime`

I have added support for OffsetDateTime in my application:

    @Override
    public OffsetDateTime deserialize(VPackSlice parent,
                                      VPackSlice vpack,
                                      VPackDeserializationContext context)
            throws VPackException {
        return OffsetDateTime.parse(vpack.getAsString(),
                java.time.format.DateTimeFormatter.ISO_OFFSET_DATE_TIME);
    }

    @Override
    public void serialize(VPackBuilder builder,
                          String attribute,
                          OffsetDateTime offsetDateTime,
                          VPackSerializationContext context)
            throws VPackException {
        builder.add(attribute, 
                offsetDateTime.format(java.time.format.DateTimeFormatter.ISO_OFFSET_DATE_TIME));
    }

But i worry that the support might be added in this module with a different/incompatible implementation.

**Comment by mvollmary** [comment]
Hi, @gontard 

thanks for your input. I added support for `ZonedDateTime`, `OffsetDateTime` and `ZoneId`.
Because I want every time/date type compatible with the persisted date format I have to save every type with the pattern `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'` (ISO 8601). For this I use `SimpleDateFormat`, but for `ZonedDateTime` and `OffsetDateTime` I also implemented a fallback solution which does the same as your implementation of the deserializer. So it should still compatible with your already persisted data.
I added some compatibility tests to ensure that. Take a look [here](https://github.com/arangodb/java-velocypack-module-jdk8/blob/master/src/test/java/com/arangodb/velocypack/module/jdk8/VPackTimeTest.java#L210).

Would be nice if you can get me feedback to this :-)

best
Mark

**Comment by gontard** [comment]
Hi @mpv1989 , 
thanks for your help.

My application is not in production so I can still change my serializers implementation. So I tried your implementation:

    @Override
    public OffsetDateTime deserialize(VPackSlice parent,
                                      VPackSlice vpack,
                                      VPackDeserializationContext context)
            throws VPackException {
        final Instant instant = VPackDeserializers.DATE.deserialize(parent, vpack, context).toInstant();
        return instant.atOffset(ZoneId.systemDefault().getRules().getOffset(instant));
    }

    @Override
    public void serialize(VPackBuilder builder,
                          String attribute,
                          OffsetDateTime value,
                          VPackSerializationContext context)
            throws VPackException {
        VPackJdk8Serializers.INSTANT.serialize(builder, attribute, value.toInstant(), context);
    }

and it works perfectly (for me). I will use this implementation now. (I don't need the fallbacks based on ISO_OFFSET_DATE_TIME).

Note that the serialized/deserialized date are not really equals (the zone offset is lost). But it is sufficient for me.

I wrote this test to test this case:

	@Test
	public void offsetDateTime() {
		OffsetDateTime out = OffsetDateTime.parse("2007-12-03T10:15:30+05:00");
		System.out.println(out);
		VPackSlice serializedDate = vp.serialize(out);
		OffsetDateTime in = vp.deserialize(serializedDate, OffsetDateTime.class);;
		assertThat(in.isEqual(out), is(true)); // instant are equals
    //         assertThat(in, is(out)); // not equals
	}


Thanks again.

**Comment by mvollmary** [comment]
Thanks for your feedback. I think we can stay with this solution even if we lost the zone offset. It's more important for me to have compatibility between the date types.

I released version `1.0.3` with the changes.

**Comment by gontard** [comment]
OK, excellent. I will test the [`1.0.3`](https://github.com/arangodb/java-velocypack-module-jdk8/releases/tag/1.0.3) right now.
